---
title: "Week 2: Starting with R"
author: "UZH n UU: tested by Jonas"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2: default
  bookdown::pdf_document2: default
bibliography: bibliography.bib
---

```{r load libraries, include=FALSE}
# install readr from CRAN
# install.packages("readr")
library(readr) # make sure your R has this library loaded, if not install it (see line above)
```

# Exercises for the R-Beginner - The fancy calculator

## Exercise 3
### 3.5
```{r myN, echo=TRUE, include=TRUE}
whale <- read.table(file = '~/Github/OmicsInOncology_Group_6/week2/data4exercises/mywhaledata.tsv', header = TRUE, stringsAsFactors = FALSE, sep = "\t")
dim(whale)
```

### 3.6
```{r lg10, echo=TRUE, include=TRUE}
head(whale)
names(whale)
str(whale)
```

### 3.7
```{r sessionInfo, echo=TRUE, include=TRUE}
summary(whale)
#Number.whales misses one value as it says NA's :1
```

### 3.9
```{r sessionInfo, echo=TRUE, include=TRUE}
whale_1200 <- whale[whale$depth > 1200, ]
whale_200 <- whale[whale$gradient > 200, ]
whale_low <- whale[whale$whater.noise == "low",]
whale_high_may <- whale[whale$water.noise == "high" & whale$month == "May",]
whale_october_details <- whale[whale$water.noise == "low" & whale$month == "October" & whale$gradient > 132,]
whale_lat_long_defined <- whale[whale$latitude > 60 & whale$latitude < 61 & whale$longitude> -6 & whale$longitude < -4,]
whale_water_notmed <- whale[whale$water.noise != "medium",]
```

###3.10
```{r sessionInfo, echo=TRUE, include=TRUE}
whale_october_details <- whale[whale$water.noise == "low" & whale$month == "October" & whale$gradient > median(whale$gradient),]
```

###3.11
```{r sessionInfo, echo=TRUE, include=TRUE}
whale_extract <- whale[whale$depth > 1500 & whale$number.whales > mean(whale$number.whales),]
#The problem with the outcome to be defined
```








